### ISSUE TITLE
Forge Version

### ISSUE THREAD

**Issue by UltimateGG** [dragon-forge/HammerMicroblocks#1]
When I try to run on a Forge server (47.2.0 for MC 1.20.1) and downloaded this mod from CurseForge that says for 1.20.1 (20.1.8) it throws an error
Failure message: Mod File HammerMicroblocks-1.20.1-20.1.8.jar needs language provider javafml:47.1 or above to load
                We have found 47

I am on the latest version of Forge for 1.20.1

**Comment by Zeitheron** [comment]
You need neoforge.

**Comment by UltimateGG** [comment]
Thank you, on CurseForge I think you can mark the mod loader version as NeoForge specifically it shows just Forge currently
